#!/usr/bin/env bash
#
# Push the current branch to origin, rebasing and retrying when another
# writer beats us to the ref.
#
# main has several concurrent writers: this repo's workflows (generate-feed,
# the six weekly-maintenance jobs) plus review.html, which commits
# feedback/*.json through the GitHub API with REVIEW_PAT at whatever time the
# user rates articles. A plain `git push` fails with "fetch first" whenever one
# of those lands between checkout and push, and even `pull --rebase && push`
# loses the race if a commit arrives in the gap between the two.
#
# Usage: git_push_retry.sh [branch]   (branch defaults to main)
#
# Rebase conflicts are auto-resolved in favour of this run only for
# machine-generated artifacts (caches, logs, reports) — those are regenerated
# wholesale every run, so the newest writer is authoritative. A conflict in
# any hand-editable file (config/, feeds.opml, source) aborts the rebase and
# fails the step rather than silently discarding someone's edit.

set -euo pipefail

BRANCH="${1:-main}"
MAX_ATTEMPTS=5

# Files regenerated by the pipeline each run: safe to resolve as "ours".
GENERATED_PATTERNS=(
  '*_cache.json'
  'calibration_memory/*'
  'article_review_audit_summary.json'
  'shared_source_candidates.json'
  'weekly-state-article.json'
  'FEED_LOG.md'
  'FEED_ERRORS.md'
  'CALIBRATION_LOG.md'
  'FEED_HEALTH_LOG.md'
  'FEEDBACK_TRAINING_LOG.md'
  'SHARED_ARTICLES_LOG.md'
  'FEED_REVIEW_*.md'
  'CORPUS_ALIGNMENT_REPORT_*.md'
  'ARTICLE_REVIEW_AUDIT_*.md'
  'weekly-report-*.html'
  'tools/filter_priority_review.md'
)

is_generated() {
  local path="$1" pattern
  for pattern in "${GENERATED_PATTERNS[@]}"; do
    # shellcheck disable=SC2053  # glob match is intentional
    [[ "$path" == $pattern ]] && return 0
  done
  return 1
}

# Resolve conflicts left by a failed rebase step. Returns non-zero if any
# conflicted path is not a generated artifact.
resolve_generated_conflicts() {
  local conflicted path
  conflicted="$(git diff --name-only --diff-filter=U)"
  [ -z "$conflicted" ] && return 0

  while IFS= read -r path; do
    if ! is_generated "$path"; then
      echo "Conflict in non-generated file: $path" >&2
      return 1
    fi
    # Mid-rebase HEAD is the upstream branch and the replayed commit is
    # "theirs", so --theirs selects this run's freshly generated version.
    git checkout --theirs -- "$path" || return 1
    git add -- "$path"
  done <<< "$conflicted"

  return 0
}

# Replay our commits on top of origin/$BRANCH, resolving generated-file
# conflicts as we go. Aborts the rebase and returns non-zero on anything else.
rebase_onto_remote() {
  if git rebase --autostash "origin/$BRANCH"; then
    return 0
  fi

  while true; do
    if ! resolve_generated_conflicts; then
      git rebase --abort || true
      return 1
    fi
    # A conflict resolved to an empty diff means the change is already
    # upstream; --skip is the only way forward for that commit.
    if git diff --cached --quiet; then
      git rebase --skip && return 0
    else
      git -c core.editor=true rebase --continue && return 0
    fi
    if [ -z "$(git diff --name-only --diff-filter=U)" ]; then
      git rebase --abort || true
      return 1
    fi
  done
}

for attempt in $(seq 1 "$MAX_ATTEMPTS"); do
  if git push origin "HEAD:$BRANCH"; then
    echo "Pushed to $BRANCH on attempt $attempt."
    exit 0
  fi

  if [ "$attempt" -eq "$MAX_ATTEMPTS" ]; then
    break
  fi

  backoff=$((2 ** attempt))
  echo "Push to $BRANCH rejected (attempt $attempt/$MAX_ATTEMPTS); \
rebasing onto origin/$BRANCH and retrying in ${backoff}s..." >&2
  sleep "$backoff"

  git fetch origin "$BRANCH"
  if ! rebase_onto_remote; then
    echo "Rebase onto origin/$BRANCH failed; manual resolution required." >&2
    exit 1
  fi
done

echo "Failed to push to $BRANCH after $MAX_ATTEMPTS attempts." >&2
exit 1
